fitness/fitness/urls.py
from django.contrib import admin
from django.urls import path
from reservations import views
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = 'index'),
    path('gym/<int:gym_id>',views.gym, name='gym'),
    path('gym/<int:gym_id>/addreservation',views.addreservation, name='addreservation'),
]
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = 'index'),
    path('add',views.gym_add, name='gym_add'),
    path('addnewgym',views.addnewgym, name='addnewgym'),
    path('gym/<int:gym_id>',views.gym, name='gym'),
    path('gym/<int:gym_id>/user/add',views.user_add, name='user_add'),
    path('gym/<int:gym_id>/user/adduser',views.adduser, name='adduser'),
    
    
    path('gym/<int:gym_id>/instructor/add',views.instructor_add, name='instructor_add'),
    path('gym/<int:gym_id>/instructor/addinstructor',views.addinstructor, name='addinstructor'),
    
    path('gym/<int:gym_id>/workout/add',views.workout_add, name='workout_add'),
    path('gym/<int:gym_id>/workout/adduser',views.addworkout, name='addworkout'),
    
    path('gym/<int:gym_id>/user/<int:user_id>',views.user_detail_main, name='user_detail_main'),
    path('gym/<int:gym_id>/instructor/<int:instructor_id>',views.instructor_detail_main, name='instructor_detail_main'),
    path('gym/<int:gym_id>/workout/<int:workout_id>/instructor/<int:instructor_id>',views.instructor_detail_main_2, name='instructor_detail_main_2'),
    
    
    path('gym/<int:gym_id>/workout/<int:workout_id>',views.workout_detail_main, name='workout_detail_main'),
    path('gym/<int:gym_id>/workout/<int:workout_id>/equipment/<int:equipment_id>',views.equipment_detail_main, name='equipment_detail_main'),
    
    path('gym/<int:gym_id>/addreservation',views.addreservation, name='addreservation'),
    path('gym/<int:gym_id>/add',views.reservation_add, name='reservation_add'),
    path('gym/<int:gym_id>/reservation/<int:reservation_id>/', views.reservation_detail, name='reservation_detail'),
    path('gym/<int:gym_id>/reservation/<int:reservation_id>/user/<int:user_id>', views.user_detail, name='user_detail'),
    path('gym/<int:gym_id>/reservation/<int:reservation_id>/workout/<int:workout_id>', views.workout_detail, name='workout_detail'),
    path('gym/<int:gym_id>/reservation/<int:reservation_id>/workout/<int:workout_id>/instructor/<int:instructor_id>', views.instructor_detail, name='instructor_detail'),
    path('gym/<int:gym_id>/reservation/<int:reservation_id>/workout/<int:workout_id>/equipment/<int:equipment_id>', views.equipment_detail, name='equipment_detail'),
]

fitness/reservations/models.py
from django.db import models

class Instructor(models.Model):
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    email = models.EmailField()
    phone_number = models.IntegerField()
    
    def __str__(self):
        return self.firstname + ' ' + self.lastname

class User(models.Model):
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    email = models.EmailField()
    age = models.IntegerField()
    password = models.CharField(max_length=30)
    
    def __str__(self):
        return self.firstname + ' ' + self.lastname

class Equipment(models.Model):
    name = models.CharField(max_length=30)
    brand = models.CharField(max_length=30)
    year_of_production = models.IntegerField()
    
    def __str__(self):
        return self.name

class Workout(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    duration = models.IntegerField()
    difficulty = models.CharField(max_length=100)
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
class Gym(models.Model):
    name = models.CharField(max_length=30)
    town = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    entry = models.IntegerField()
    
    def __str__(self):
        return self.name

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    reservation_date = models.DateField()
    gym = models.ForeignKey(Gym, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.workout.name + ' - ' + self.user.firstname + " "+ self.user.lastname 



fitness/reservations/forms.py
from django import forms
from .models import Gym,Instructor,Equipment,Reservation,User,Workout

class ReservationForm(forms.ModelForm):
    user = forms.HiddenInput()
    class Meta():
        model = Reservation
        exclude = ['gym']
        widgets = {
            'reservation_date': forms.widgets.DateInput(attrs={'type': 'date'})
        }
        
class WorkoutForm(forms.ModelForm):
    class Meta():
        model = Workout
        exclude = []
        
        
class UserForm(forms.ModelForm):
    class Meta():
        model = User
        exclude = []        
        
class GymForm(forms.ModelForm):
    class Meta():
        model = Gym
        exclude = []
        
class InstructorForm(forms.ModelForm):
    class Meta():
        model = Instructor
        exclude = []
        



fitness/reservations/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.models import User
from .models import User,Instructor,Workout,Gym,Reservation,Equipment
from .forms import ReservationForm,WorkoutForm,GymForm,UserForm,InstructorForm
# Create your views here.

def addnewgym(request):
    g_form = GymForm(request.POST)
    if g_form.is_valid():
        name = g_form.cleaned_data['name']
        town = g_form.cleaned_data['town']
        description = g_form.cleaned_data['description']
        entry = g_form.cleaned_data['entry']
        gym = Gym(
            name=name,
            town=town,
            description=description,
            entry=entry,
        )
        gym.save()
        return redirect('index')
    
def instructor_detail_main(request,gym_id,instructor_id):
    instructor = get_object_or_404(Instructor, pk=instructor_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/instructor_detail_main.html', {'instructor': instructor,'gym' : gym})
    
    
def instructor_detail_main_2(request,gym_id,instructor_id):
    instructor = get_object_or_404(Instructor, pk=instructor_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/instructor_detail_main_2.html', {'instructor': instructor,'gym' : gym})
 
    
    
def user_detail_main(request,gym_id,user_id):
    user = get_object_or_404(User, pk=user_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/user_detail_main.html', {'user': user,'gym' : gym})

def workout_detail_main(request,gym_id,workout_id):
    workout = get_object_or_404(Workout, pk=workout_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/workout_detail_main.html', {'workout': workout,'gym' : gym})

def index(request):
    gyms = Gym.objects.all()
    return render(request,'reservations/index.html',{'gyms':gyms})

def gym_add(request):
    gym_form = GymForm(request.POST)
    return render(request, 'reservations/gym_add.html', {'gym_form' : gym_form})


def gym(request,gym_id):
    instructors = Instructor.objects.all()
    workouts = Workout.objects.all()
    users = User.objects.all()
    gym = get_object_or_404(Gym,pk = gym_id)
    reservations =  Reservation.objects.filter(gym = gym)
    reservation_form = ReservationForm()
    return render(request,'reservations/gym.html',{'instructors' : instructors ,'users' : users,'workouts' : workouts,'gym' : gym, 'reservations' : reservations,'reservation_form' : reservation_form})

def user_add(request,gym_id):
    gym = get_object_or_404(Gym,pk = gym_id)
    user_form = UserForm(request.POST)
    return render(request, 'reservations/user_add.html', {'user_form' : user_form, 'gym' : gym})
    

def adduser(request,gym_id):
    gym = get_object_or_404(Gym,pk = gym_id)
    u_form = UserForm(request.POST)
    if u_form.is_valid():
        firstname = u_form.cleaned_data['firstname']
        lastname = u_form.cleaned_data['lastname']
        email = u_form.cleaned_data['email']
        age = u_form.cleaned_data['age']
        password = u_form.cleaned_data['password']
        user = User(
            firstname=firstname,
            lastname=lastname,
            email=email,
            age=age,
            password=password,
        )
        user.save()
        return redirect('gym', gym_id=gym.id)
    
    
    
def instructor_add(request,gym_id):
    gym = get_object_or_404(Gym,pk = gym_id)
    instructor_form = InstructorForm(request.POST)
    return render(request, 'reservations/instructor_add.html', {'instructor_form' : instructor_form, 'gym' : gym})
    

def addinstructor(request,gym_id):
    gym = get_object_or_404(Gym,pk = gym_id)
    i_form = InstructorForm(request.POST)
    if i_form.is_valid():
        firstname = i_form.cleaned_data['firstname']
        lastname = i_form.cleaned_data['lastname']
        email = i_form.cleaned_data['email']
        phone_number = i_form.cleaned_data['phone_number']
        instructor = Instructor(
            firstname=firstname,
            lastname=lastname,
            email=email,
            phone_number=phone_number,
        )
        instructor.save()
        return redirect('gym', gym_id=gym.id)
    
    
    
def workout_add(request,gym_id):
    gym = get_object_or_404(Gym,pk = gym_id)
    workout_form = WorkoutForm(request.POST)
    return render(request, 'reservations/workout_add.html', {'workout_form' : workout_form, 'gym' : gym})
    

def addworkout(request,gym_id):
    gym = get_object_or_404(Gym,pk = gym_id)
    w_form = WorkoutForm(request.POST)
    if w_form.is_valid():
        name = w_form.cleaned_data['name']
        description = w_form.cleaned_data['description']
        duration = w_form.cleaned_data['duration']
        difficulty = w_form.cleaned_data['difficulty']
        instructor = w_form.cleaned_data['instructor']
        equipment = w_form.cleaned_data['equipment']
        workout = Workout(
            name=name,
            description=description,
            duration=duration,
            difficulty=difficulty,
            instructor=instructor,
            equipment=equipment,
        )
        workout.save()
        return redirect('gym', gym_id=gym.id)
    
    
    
    
def reservation_add(request, gym_id):
    gym = get_object_or_404(Gym,pk = gym_id)
    reservation_form = ReservationForm()
    return render(request, 'reservations/reservation_add.html', {'gym' : gym,'reservation_form' : reservation_form})



def addreservation(request,gym_id):
    gym = get_object_or_404(Gym,pk = gym_id)
    r_form = ReservationForm(request.POST)
    if r_form.is_valid():
        reservation_date = r_form.cleaned_data['reservation_date']
        user = r_form.cleaned_data['user']
        workout = r_form.cleaned_data['workout']
        reservation = Reservation(
            reservation_date=reservation_date,
            gym=gym,
            user=user,
            workout=workout,
        )
        reservation.save()
        return redirect('gym', gym_id=gym.id)
    
def reservation_detail(request, gym_id, reservation_id):
    reservation = get_object_or_404(Reservation, pk=reservation_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/reservation_detail.html', {'reservation': reservation,'gym' : gym})

def user_detail(request,gym_id, reservation_id, user_id):
    user = get_object_or_404(User, pk=user_id)
    reservation = get_object_or_404(Reservation, pk=reservation_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/user_detail.html', {'user': user,'reservation': reservation,'gym' : gym})


def instructor_detail(request,gym_id, reservation_id,workout_id, instructor_id):
    instructor = get_object_or_404(Instructor, pk=instructor_id)
    workout = get_object_or_404(Workout, pk=workout_id)
    reservation = get_object_or_404(Reservation, pk=reservation_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/instructor_detail.html', {'workout' : workout ,'instructor': instructor,'reservation': reservation,'gym' : gym})


def workout_detail(request,gym_id, reservation_id, workout_id):
    workout = get_object_or_404(Workout, pk=workout_id)
    reservation = get_object_or_404(Reservation, pk=reservation_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/workout_detail.html', {'workout': workout,'reservation': reservation,'gym' : gym})

def equipment_detail(request,gym_id, reservation_id, workout_id,equipment_id):
    equipment = get_object_or_404(Equipment, pk=equipment_id)
    workout = get_object_or_404(Workout, pk=workout_id)
    reservation = get_object_or_404(Reservation, pk=reservation_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/equipment_detail.html', {'workout': workout,'reservation': reservation,'gym' : gym, 'equipment' : equipment})

def equipment_detail_main(request,gym_id, workout_id,equipment_id):
    equipment = get_object_or_404(Equipment, pk=equipment_id)
    workout = get_object_or_404(Workout, pk=workout_id)
    gym = get_object_or_404(Gym,pk = gym_id)
    return render(request, 'reservations/equipment_detail_main.html', {'workout': workout,'gym' : gym, 'equipment' : equipment})




fitness/templates/reservations/equipment_detail.html
<!DOCTYPE html>
<html>
<head>
	<title>Equipment</title>
</head>
<body>

    <h2>-------------------------------------------------------------------------------------------------------</h1>
        <h1><a class="back" href = "{% url 'workout_detail' gym.id reservation.id reservation.workout.id %}"> Back</a>Equipment Detail</h1>
        <h2>-------------------------------------------------------------------------------------------------------</h1>
	
	<ul class = "left">
        <ul class="bordering">
		<li>
			Name: 
		</li>
        <li class = "move_left">
			{{reservation.workout.equipment.name}}
		</li>
    </ul>

    <ul class="bordering">
		<li>
			Duration: 
		</li>
        <li class = "move_left">
			{{reservation.workout.equipment.brand}}
		</li>
    </ul>

    </ul>
    <ul class= "right">
		<ul class="bordering">
            <li>
                Difficulty: 
            </li>
            <li class = "move_left" >
				{{reservation.workout.equipment.year_of_production}}

            </li>
        </ul>
    

	</ul>

    <style>
        .bordering
        {
            margin-top: 20px;
            border-style: solid;
            border-width: 2px;
            border-color: grey;
            border-radius: 10px;
        }
        .move_left
        {
            font-weight: bold;
            margin-right: 30px;
            margin-bottom: 20px;
            text-align: center;
        }

        .move_left_censored
        {
            font-weight: bold;
            margin-left: 40px;
            margin-right: 10px;
            margin-bottom: 20px;
            text-decoration: line-through;
        }

        .left
            {
                
                margin-left : 30%;
                float : left;
            }
            li
            {
                margin-top : 20px;
            }

            .right
            {
                margin-right : 30%;
                float : right;
            }
            ul
            {
                list-style-type: none;
            }
        body
        {
            background-color: #FAEBD7;
            font-family: Arial, sans-serif;
            font-size: 22px;
            
        }
        .back
            {
                display  :flex;
               margin-right : 40%;
            }
            h1
            {
                
                display  :flex;
                text-align : center;
            }
            h2
            {
                text-align : center;
            }
    </style>

</body>
</html>

fitness/templates/reservations/equipment_detail_main.html
<!DOCTYPE html>
<html>
<head>
	<title>Equipment</title>
</head>
<body>

    <h2>-------------------------------------------------------------------------------------------------------</h1>
        <h1><a class="back" href = "{% url 'gym' gym.id %}"> Back</a>Equipment Detail</h1>
        <h2>-------------------------------------------------------------------------------------------------------</h1>
	
	<ul class = "left">
        <ul class="bordering">
		<li>
			Name: 
		</li>
        <li class = "move_left">
			{{workout.equipment.name}}
		</li>
    </ul>

    <ul class="bordering">
		<li>
			Duration: 
		</li>
        <li class = "move_left">
			{{workout.equipment.brand}}
		</li>
    </ul>

    </ul>
    <ul class= "right">
		<ul class="bordering">
            <li>
                Difficulty: 
            </li>
            <li class = "move_left" >
				{{workout.equipment.year_of_production}}

            </li>
        </ul>
    

	</ul>

    <style>
        .bordering
        {
            margin-top: 20px;
            border-style: solid;
            border-width: 2px;
            border-color: grey;
            border-radius: 10px;
        }
        .move_left
        {
            font-weight: bold;
            margin-right: 30px;
            margin-bottom: 20px;
            text-align: center;
        }

        .move_left_censored
        {
            font-weight: bold;
            margin-left: 40px;
            margin-right: 10px;
            margin-bottom: 20px;
            text-decoration: line-through;
        }

        .left
            {
                
                margin-left : 30%;
                float : left;
            }
            li
            {
                margin-top : 20px;
            }

            .right
            {
                margin-right : 30%;
                float : right;
            }
            ul
            {
                list-style-type: none;
            }
        body
        {
            background-color: #FAEBD7;
            font-family: Arial, sans-serif;
            font-size: 22px;
            
        }
        .back
            {
                display  :flex;
               margin-right : 40%;
            }
            h1
            {
                
                display  :flex;
                text-align : center;
            }
            h2
            {
                text-align : center;
            }
    </style>

</body>
</html>

fitness/templates/reservations/gym.html
<html>
    <body>
        <h2>-------------------------------------------------------------------------------------------------------</h1>
        <h1><a class="back" href = "{% url 'index' %}"> Back</a>{{gym.name}}</h1>
        <h2>-------------------------------------------------------------------------------------------------------</h1>
        <p class ="gym_main">Town: {{gym.town}}</p>
        <p class ="gym_main" >Type of Gym: {{gym.description}}</p>
        <p class ="gym_main">Entry: {{gym.entry}},-</p>
        
    
        {% if gym.reservation_set.all %}
            <h3>Reservations:</h3>
            <ul class = "ul_middle">
                {% for reservation in gym.reservation_set.all %}
                <li><a href="{% url 'reservation_detail' gym.id reservation.id %}">#{{ reservation.id }} Reservation</a></li>
            {% endfor %}
            <a href="{% url 'reservation_add' gym.id%}"><button type="button">Add new Reservation</button></a>
            </ul>


            <h3>Instructors:</h3>
            <ul class = "ul_middle">
                {% for instructor in instructors %}
                <li><a href="{% url 'instructor_detail_main' gym.id instructor.id %}">{{ instructor.firstname }} {{ instructor.lastname }} </a></li>
            {% endfor %}
            <a href="{% url 'instructor_add' gym.id%}"><button type="button">Add new Instructor</button></a>
            </ul>


        {% else %}
            <p>No reservations yet.</p>
        {% endif %}

        <ul class="left" >
            <li class = "main_ul">Available workouts:</li>
        {% for w in workouts %}
        <li>
            <li><a href="{% url 'workout_detail_main' gym.id w.id %}">{{w.name}} </a></li>
        
        </li>
        {% endfor %}
        <a href="{% url 'workout_add' gym.id %}"><button type="button">Add new Workout</button></a>
        </ul>

        <ul class="right">
            <li class = "main_ul">Users:</li>
            {% for user in users %}
            <li>
                <a href="{% url 'user_detail_main' gym.id user.id %}"> {{user.firstname}}  {{user.lastname}}</a>
            </li>
            {% endfor %}
            <a href="{% url 'user_add' gym.id %}"><button type="button">Add new User</button></a>
            </ul>


            

       

        
        <style>
    button 
    {
        margin-bottom : 20px;
        background-color: #3CB371;
        color: white;
        padding: 10px 10px;
        border-radius: 5px;
        font-size: 18px;
        margin-top: 30px;
        
    }
    button:hover 
    {
        background-color: #006400;
    }
    ul
    {
        list-style-type: none;
    }
            .ul_middle
            {
                list-style-type: none;
                text-align: center;
            }
            h3
            {
                text-align: center;
            }
            .back
            {
                display  :flex;
               margin-right : 44%;
            }
            h1
            {
                
                display  :flex;
                text-align : center;
            }

            
            body
            {
                background-color: #FAEBD7;
                font-family: Arial, sans-serif;
                font-size: 18px;
            }
            a
            {
                text-decoration: none;
            
            }
            h2
            {
                text-align : center;
            }

            .gym_main
            {
                text-align : center;
                font-size: 22px;
            }

            .left
            {
                margin-left : 35%;
                float : left;
            }

            .right
            {
                margin-right : 35%;
                float : right;
            }

            .main_ul
            {
                font-weight: bold;
                list-style-type: none;
                font-size: 20px;
            }
        </style>
    
    </body>
</html

fitness/templates/reservations/index.html
<html>
<body>
    <h1>------------------------------------------------List of Gyms------------------------------------------------</h1>
    {% for gym in gyms%}
        <h2><a href="{% url 'gym' gym.id %}">{{gym.name}}</a></h2>
    {% endfor%}
</body>





<h1>------------------------------------------------------------------------------------------------------------------</h1>
<a href="{% url 'gym_add'%}"><button type="button">Add new Gym</button></a>

<style>

    body {
        background-color: #FAEBD7;
        font-family: Arial, sans-serif;
    }
    h1 {
        font-size: 35px;
        text-align: center;
        margin-top: 50px;
    }
    h2 {
        margin-top: 40px;
        text-align: center;
    }
    a 
    {
        text-decoration: none;
        color: black;
    }
    h2:hover
    {
        font-size: 30px;
    }
    button 
    {
        background-color: #3CB371;
        color: white;
        padding: 10px 10px;
        border-radius: 5px;
        font-size: 18px;
        display: block;
        margin: auto;
        
    }
    button:hover 
    {
        background-color: #006400;
    }

</style>

</html>

fitness/templates/reservations/instructor_add.html
<html>
<body>

    <h2><a href="{% url 'gym' gym.id %}"> Back</a></h2>
    <h1> Add Instructor</h1>
    
    <form action = "{% url 'addinstructor' gym.id %}" method="POST">
        {% csrf_token %}
            {{instructor_form.as_p}}
            <a href="{% url 'gym' gym.id  %}"><input type ="submit" value ="Submit"> </input></a>

    </form>

    <style>

        body
        {
            background-color: #FAEBD7;
            font-family: Arial, sans-serif;
            font-size: 22px;
            
        }
        form 
        {
            margin-left: 500px;
            margin-right: 500px;
            
            border-radius: 5px;
        }
        label 
        {
            display: block;
            text-align :center;
        }
        input[type=text], input[type=date] , input[type=number],input[type=email]
        {
            width: 50%;
            padding: 12px 20px;
            margin: 8px 0;
            margin-left: 25%;
            
            border-radius: 4px;
        }
        input[type=submit]
        {
            width: 10%;
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            margin-left: 45%;
        }
        input[type=submit]:hover {
            background-color: #45a049;
        }
        header {
            background-color: #333;
            color: white;
            padding: 20px;
            text-align: center;
        }
        h1 {
            margin: 0;
        }
        a {
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        h1 {
            text-align : center;
        }

    </style>
</body>
</html>

fitness/templates/reservations/instructor_detail_main.html
<!DOCTYPE html>
<html>
<head>
	<title>Instructor</title>
</head>
<body>
    <h2>-------------------------------------------------------------------------------------------------------</h1>
        <h1><a class="back" href = "{% url 'index' %}"> Back</a>Instructor Detail</h1>
        <h2>-------------------------------------------------------------------------------------------------------</h1>
	
	<ul class = "left">
        <ul class="bordering">
		<li>
			Name: 
		</li>
        <li class = "move_left">
			{{instructor.firstname}}
			{{instructor.lastname}}
		</li>
    </ul>

    <ul class="bordering">
		<li>
			Email: 
		</li>
        <li class = "move_left">
			{{instructor.email}}
		</li>
    </ul>

    </ul>
    <ul class= "right">
		<ul class="bordering">
            <li>
                Phone number: 
            </li>
            <li class = "move_left" >
                {{instructor.phone_number}}
            </li>
        </ul>
    


    <style>
        .bordering
        {
            margin-top: 20px;
            border-style: solid;
            border-width: 2px;
            border-color: grey;
            border-radius: 10px;
        }
        .move_left
        {
            font-weight: bold;
            margin-right: 30px;
            margin-bottom: 20px;
            text-align: center;
        }

        .move_left_censored
        {
            font-weight: bold;
            margin-left: 40px;
            margin-right: 10px;
            margin-bottom: 20px;
            text-decoration: line-through;
        }

        .left
            {
                
                margin-left : 30%;
                float : left;
            }
            li
            {
                margin-top : 20px;
            }

            .right
            {
                margin-right : 30%;
                float : right;
            }
            ul
            {
                list-style-type: none;
            }
        body
        {
            background-color: #FAEBD7;
            font-family: Arial, sans-serif;
            font-size: 22px;
            
        }
        .back
            {
                display  :flex;
               margin-right : 40%;
            }
            h1
            {
                
                display  :flex;
                text-align : center;
            }
            h2
            {
                text-align : center;
            }
    </style>

</body>
</html>

fitness/templates/reservations/reservation_add.html
<!DOCTYPE html>
<html>
<head>
	<title>Reservation Details</title>
</head>
<body>

   
    <h2><a href="{% url 'gym' gym.id %}"> Back</a></h2>

    <h1>Add Reservation</h1>
        <form action = "{% url 'addreservation' gym.id %}" method="POST">
            {% csrf_token %}
                {{reservation_form.as_p}}
                <a href="{% url 'gym' gym.id %}"><input type ="submit" value ="Submit"> </input></a>

        </form>

        <style>

            body
            {
                background-color: #FAEBD7;
                font-family: Arial, sans-serif;
                font-size: 22px;
                
            }
            form 
            {
                margin-left: 500px;
                margin-right: 500px;
                
                border-radius: 5px;
            }
            label 
            {
                display: block;
                text-align :center;
            }
            input[type=text], input[type=date] , input[type=number],input[type=email],select
            {
                width: 50%;
                padding: 12px 20px;
                margin: 8px 0;
                margin-left: 25%;
                
                border-radius: 4px;
            }
            input[type=submit]
            {
                width: 10%;
                background-color: #4CAF50;
                color: white;
                padding: 12px 20px;
                border: none;
                border-radius: 4px;
                margin-left: 45%;
            }
            input[type=submit]:hover {
                background-color: #45a049;
            }
    
            header {
                background-color: #333;
                color: white;
                padding: 20px;
                text-align: center;
            }
            h1 {
                text-align : center;
            }

            a {
               
                text-decoration: none;
            }
            a:hover {
                text-decoration: underline;
            }
    
        </style>
</body>
</html>